# SwiftLint Configuration for SpeechToText macOS App

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - function_body_length
  - file_length

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_imports
  - closure_spacing
  - operator_usage_whitespace

excluded:
  - .build
  - build
  - DerivedData
  - Tests
  - Resources
  - xcode-project

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - db
    - ui
    - ax

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

reporter: "xcode"

# Custom rules to catch common Swift concurrency issues
custom_rules:
  # Detect @Observable classes with actor existential properties that aren't @ObservationIgnored
  # This pattern can cause crashes due to executor check failures
  observable_actor_existential_warning:
    name: "Observable Actor Existential"
    regex: '@Observable[\s\S]*?private\s+let\s+\w+:\s*any\s+\w*(?:Protocol|Service)'
    message: "Actor existential types in @Observable classes should use @ObservationIgnored to prevent executor check crashes"
    severity: warning
    match_kinds:
      - comment
      - comment.mark
      - comment.url
      - doccomment
      - doccomment.field
    excluded: true  # Only match in source code, not comments

  # Note: nonisolated(unsafe) is intentionally used for deinit cleanup patterns
  # where MainActor-isolated state cannot be accessed. This is safe when used with
  # thread-safe operations like Timer.invalidate() or NSLock-protected state.
  # See docs/CONCURRENCY_PATTERNS.md for details on safe usage.
